version: '3.8'
services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-airbnb}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-airbnb}
      POSTGRES_DB: ${DB_NAME:-rental_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 